app/__init__.py
from flask import Flask
from .config import config
from app.blueprints.main import main as main_blueprint
from app.blueprints.auth import auth as auth_blueprint


def create_app(config_name="default"):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)

    return app

app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/blueprints/main/routes.py
from flask import render_template
from . import main

@main.route('/')
def home():
    return render_template('index.html')

@main.route('/explainer')
def explainer():
    return render_template('video.html')

app/templates/components/Navbar.html
<header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo d-flex align-items-center">
        <a href="{{url_for('main.home')}}" class="me-2"><img src="{{url_for('static',filename='img/youtube.png')}}" alt="" class="img-fluid"></a>
        <h1 class="fw-bold"><a href="{{url_for('main.home')}}"><span>TubeExplainer</span></a></h1>
      </div>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link px-4 btn login_btn px-5" style="font-size:16px" href="{{url_for('auth.login')}}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link login_btn px-5 mx-2 btn " style="font-size:17px;" href="{{ url_for('auth.register') }}">Register</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    </div>
  </header>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>TubeExplainer</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="url_for('static',filename='img/youtube.png')}}" rel="icon">

  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link href="{{url_for('static',filename='css/style.css')}}" rel="stylesheet">

</head>

<body>

  {% include 'components/Navbar.html' %}
  

{% block content %}

<section id="hero" class="d-flex align-items-center">

  <div class="container">
    <div class="row gy-4">
      <div class="col-lg-6 order-2 order-lg-1 d-flex flex-column justify-content-center">
        <h1>Explain Long Youtube Video In No Time </h1>
        <h2>Langchain, OpenAI, whisper</h2>
        <div>
          <a href="{{url_for('main.explainer')}}" class="btn-get-started getstarted px-5 text-white btn rounded rounded-3 fs-5">Get Started</a>
        </div>
      </div>
      <div class="col-lg-6 order-1 order-lg-2 hero-img">
        <img src="{{url_for('static',filename='img/hero-img.svg')}}" class="img-fluid animated" alt="">
      </div>
    </div>
  </div>

</section>

<main id="main">

  <section id="about" class="about">
    <div class="container">

      <div class="row justify-content-between">
        <div class="col-lg-5 d-flex align-items-center justify-content-center about-img">
          <img src="{{url_for('static',filename='img/about-img.svg')}}" class="img-fluid" alt="" data-aos="zoom-in">
        </div>
        <div class="col-lg-6 pt-5 pt-lg-0">
          <h3 data-aos="fade-up">YouTube Transcription QA</h3>
          <p data-aos="fade-up" data-aos-delay="100">
            An end-to-end example of doing question answering on YouTube transcripts
          </p>
          <div class="row">
            <div class="col-md-6" data-aos="fade-up" data-aos-delay="100">
              <i class="bx bx-receipt"></i>
              <h4>Whisper Model</h4>
              <p>Whisper model is used to generate transcript from youtube video'audio which generated by pytube</p>
            </div>
            <div class="col-md-6" data-aos="fade-up" data-aos-delay="200">
              <i class="bx bx-cube-alt"></i>
              <h4>Main Used Tool</h4>
              <p>
                <p>
                    (VectorDBQAWithSourcesChain) : does the lookup of the documents from a vector database.
                    (CharacterTextSplitter): split up that text into chunks.                     
                    (OpenAIEmbeddings) : Embedding the generated texts.
                   
                  </p>
              </p>
            </div>
          </div>
        </div>
      </div>

    </div>
  </section>

</main>

{% endblock content %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

<footer class="container text-center mx-auto" style="position:fixed;bottom:0">
  <p class="float-end"><a href="#">Back to top</a></p>
  <p>© 2023 aboneda, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
</footer>
<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


</html>

app/templates/video.html
{% extends 'index.html' %}

{% block content %}


<div class="mt-5 pt-5">
  <form class="w-50 mx-auto mt-5 pt-5">
    <div class="mb-3 d-flex">
      <input placeholder="Video URL..." type="email" class="form-control" id="exampleInputEmail1" style="border-color:#454340;border-radius: 0;" aria-describedby="emailHelp">
      <a class="btn form-control text-dark  login_btn w-25" style="border-radius: 0;">Submit</a>
    </div>
  </form>
</div>


<div class="">
  <form class="w-50 mx-auto ">
    <div class="mb-3 d-flex">
      <input placeholder="Ask Question..." type="email" class="form-control" id="exampleInputEmail1" style="border-color:#454340;border-radius: 0;" aria-describedby="emailHelp">
      <a class="btn form-control getstarted w-25" style="border-radius: 0;">Ask Question</a>
    </div>
  </form>
</div>

<div class="w-50 mx-auto mt-4">
  <p class="fw-bold fs-5">Output</p>
<div class=" border border-3 border-secondary rounded rounded-3 " style="min-height:300px">

</div>
</div>

{% endblock content %}